version: '3'
services:
  server:
    build: .
    ports: 
    - "3000:3000"
    volumes:
    - "./:/go/src/github.com/onestay/resize-server"
    environment:
    - BUCKET_NAME=
    - AWS_ACCESS_KEY_ID=
    - AWS_SECRET_ACCESS_KEY=
    - AWS_REGION=
    - PORT=8080
    command: bash -c "go get github.com/codegangsta/gin && gin run main.go"